import { IoLogoGooglePlaystore } from "react-icons/io5";
import { FaYelp } from "react-icons/fa";
import {
  SiAppstore,
  SiArtstation,
  SiBuymeacoffee,
  SiBehance,
  SiCashapp,
  SiCodeberg,
  SiDiaspora,
  SiDiscord,
  SiDribbble,
  SiFacebook,
  SiGithub,
  SiGitlab,
  SiInstagram,
  SiLinkedin,
  SiMastodon,
  SiMedium,
  SiOpencollective,
  SiPatreon,
  SiPaypal,
  SiPeertube,
  SiPinterest,
  SiQuora,
  SiReddit,
  SiSnapchat,
  SiSoundcloud,
  SiSpotify,
  SiThreads,
  SiTumblr,
  SiTwitch,
  SiVimeo,
  SiYoutube,
} from "react-icons/si";
import { RiPixelfedFill } from "react-icons/ri";
import { BsTwitterX } from "react-icons/bs";
import { Siilo } from "@/assets/svgs/Siilo";
import { Funkwhale } from "@/assets/svgs/Funkwhale";

export const secondaryActionField = [
  {
    _id: "facebook",
    label: "Facebook",
    color: "#0866FF",
    icon: SiFacebook,
    placeholder: "username",
    linkPrefix: "https://facebook.com/",
    linkSuffix: "",
  },
  {
    _id: "instagram",
    label: "Instagram",
    color: "#DD2A7B",
    icon: SiInstagram,
    placeholder: "username",
    linkPrefix: "https://instagram.com/",
    linkSuffix: "",
  },
  {
    _id: "linkedin",
    label: "LinkedIn",
    color: "#0A66C2",
    icon: SiLinkedin,
    placeholder: "username",
    linkPrefix: "https://linkedin.com/in/",
    linkSuffix: "",
  },
  {
    _id: "github",
    label: "GitHub",
    color: "#1F2328",
    icon: SiGithub,
    placeholder: "username",
    linkPrefix: "https://github.com/",
    linkSuffix: "",
  },
  {
    _id: "threads",
    label: "Threads",
    color: "#000000",
    icon: SiThreads,
    placeholder: "username",
    linkPrefix: "https://threads.net/@",
    linkSuffix: "",
  },
  {
    _id: "twitter",
    label: "Twitter",
    color: "#0F1419",
    icon: BsTwitterX,
    placeholder: "username",
    linkPrefix: "https://twitter.com/",
    linkSuffix: "",
  },
  {
    _id: "youtube",
    label: "YouTube",
    color: "#FF0000",
    icon: SiYoutube,
    placeholder: "username",
    linkPrefix: "https://www.youtube.com/",
    linkSuffix: "",
  },
  {
    _id: "app-store",
    label: "App Store",
    color: "#147EFB",
    icon: SiAppstore,
    placeholder: "https://apps.apple.com/in/app/{appname}/id",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "art-station",
    label: "Art Station",
    color: "#13AFF0",
    icon: SiArtstation,
    placeholder: "https://artstation.com/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "behance",
    label: "Behance",
    color: "#1769FF",
    icon: SiBehance,
    placeholder: "https://behance.net/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "coffee",
    label: "Buy me a coffee",
    color: "#FFDD00",
    icon: SiBuymeacoffee,
    placeholder: "https://buymeacoffee.com/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "cash-app",
    label: "Cash App",
    color: "#00D632",
    icon: SiCashapp,
    placeholder: "https://cashapp.com/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "code-berg",
    label: "Codeberg",
    color: "#2185D0",
    icon: SiCodeberg,
    placeholder: "https://codeberg.org/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "diaspora",
    label: "Diaspora",
    color: "#000000",
    icon: SiDiaspora,
    placeholder: "https://dispora.social/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "discord",
    label: "Discord",
    color: "#5865F2",
    icon: SiDiscord,
    placeholder: "https://discord.gg/{invitecode}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "dribbble",
    label: "Dribbble",
    color: "#ED7FDF",
    icon: SiDribbble,
    placeholder: "https://dribbble.com/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "funk-whale",
    label: "Funkwhale",
    color: "#009FE3",
    icon: Funkwhale,
    placeholder: "https://funkwhale.audio/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "gitlab",
    label: "GitLab",
    color: "#E24329",
    icon: SiGitlab,
    placeholder: "https://gitlab.com/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "mastodon",
    label: "Mastodon",
    color: "#6364FF",
    icon: SiMastodon,
    placeholder: "https://mastodon.social/@{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "medium",
    label: "Medium",
    color: "#000000",
    icon: SiMedium,
    placeholder: "https://medium.com/@{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "open-collective",
    label: "Open-Collective",
    color: "#7fadf2",
    icon: SiOpencollective,
    placeholder: "https://opencollective.com/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "patreon",
    label: "Patreon",
    color: "#000000",
    icon: SiPatreon,
    placeholder: "https://patreon.com/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "paypal",
    label: "PayPal",
    color: "#0070BA",
    icon: SiPaypal,
    placeholder: "https://paypal.me/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "peertube",
    label: "Peertube",
    color: "#F2690D",
    icon: SiPeertube,
    placeholder: "https://peertube.video/{channelname}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "pinterest",
    label: "Pinterest",
    color: "#E60023",
    icon: SiPinterest,
    placeholder: "https://pinterest.com/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "pixelfed",
    label: "Pixelfed",
    color: "#6366F1",
    icon: RiPixelfedFill,
    placeholder: "https://pixelfed.social/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "play-store",
    label: "Play Store",
    color: "#4285F4",
    icon: IoLogoGooglePlaystore,
    placeholder: "https://play.google.com/store/apps/details?id={appname}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "quora",
    label: "Quora",
    color: "#B92B27",
    icon: SiQuora,
    placeholder: "https://quora.com/profile/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "reddit",
    label: "Reddit",
    color: "#FF4500",
    icon: SiReddit,
    placeholder: "https://www.reddit.com/user/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "siilo",
    label: "Siilo",
    color: "#162338",
    icon: Siilo,
    placeholder: "https://siilo.com/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "snapchat",
    label: "Snapchat",
    color: "#FFFC00",
    icon: SiSnapchat,
    placeholder: "https://snapchat.com/add/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "sound-cloud",
    label: "Soundcloud",
    color: "#FF5500",
    icon: SiSoundcloud,
    placeholder: "https://soundcloud.com/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "spotify",
    label: "Spotify",
    color: "#1ED760",
    icon: SiSpotify,
    placeholder: "https://open.spotify.com/user/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "tumblr",
    label: "Tumblr",
    color: "#001935",
    icon: SiTumblr,
    placeholder: "https://{username}.tumblr.com",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "twitch",
    label: "Twitch ",
    color: "#9147FF",
    icon: SiTwitch,
    placeholder: "https://twitch.tv/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "vimeo",
    label: "Vimeo",
    color: "#1AB7EA",
    icon: SiVimeo,
    placeholder: "https://vimeo.com/{username}",
    linkPrefix: "",
    linkSuffix: "",
  },
  {
    _id: "yelp",
    label: "Yelp",
    color: "#E00707",
    icon: FaYelp,
    placeholder: "https://yelp.com/user_details?userid={username}",
    linkPrefix: "",
    linkSuffix: "",
  },
];
